// let myArr=[0,1,2,3,4,5]
// console.log(myArr[0])
// console.log(myArr.length)
// myArr.push(6)  
// let newArr=("A",myArr)
// console.log(newArr)
// console.log(newArr.slice(1,3))
// let newArr2=("B",myArr)
// console.log(newArr2)
// console.log(newArr2.splice(2,5))
// console.log(newArr)

const myArr2=new Array(1,2,3,4,5)
console.log(myArr2)
myArr2.unshift(0) 
console.log(myArr2)
myArr2.shift()
console.log(myArr2)
console.log(myArr2.push(7))
// myArr2.pop()
console.log(myArr2)
myArr2.reverse()
console.log(myArr2)
myArr2.sort()
console.log(myArr2)