console.log(Math.random())
console.log((Math.random() *10) +1)
console.log(Math.floor(Math.random() *10) +1)
console.log(Math.ceil(4.2))
console.log(Math.floor(4.8))
console.log(Math.round(4.5))
console.log(Math.round(4.4))  
console.log(Math.max(1,2,3,4,5))
console.log(Math.min(1,2,3,4,5))    
console.log(Math.pow(2,3))
console.log(Math.sqrt(16))  
console.log(Math.abs(-5))   
console.log(Math.PI)    
let min=10
let max=20
  console.log(Math.floor(Math.random() * (max - min + 1)) + min   )